name: CI - Build & Push Docker

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependências
        run: npm install

      - name: Run tests (skip for now)
        run: |
          if npm run | grep -q " test"; then
            echo "Executando testes..."
            npm test || echo "Testes inexistentes ou falharam — continuando pipeline."
          else
            echo "Sem script de teste. Pulando etapa."
          fi

      - name: Logar no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build da imagem Docker
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/monitor:latest 

      - name: Tag com SHA do commit
        run: docker tag ${{ secrets.DOCKERHUB_USERNAME }}/monitor:latest ${{ secrets.DOCKERHUB_USERNAME }}/monitor:${{ github.sha }}

      - name: Push das imagens para o Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/monitor:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/monitor:${{ github.sha }}

      - name: Exibir informações da imagem
        run: docker images ${{ secrets.DOCKERHUB_USERNAME }}/monitor
